

# #############################  Extracted using PyRadiomics version: v3.0  ######################################

imageType:
  Original: {}
  LoG:
    sigma: [2.0, 3.0, 4.0, 5.0]
  Wavelet: {}

featureClass:
  shape2D:
  firstorder:


setting:
  # Normalization:
  normalize: true
  normalizeScale: 100

  # Resampling:
  # first dimensions always correspond to in-plane resolution.
  # Z-plane resolution should not be modified to avoid mask errors (> than 1 slice after resampling)
  interpolator: "sitkBSpline"
  resampledPixelSpacing: [2, 2, 0]
  padDistance: 10
  preCrop: true

  # 2D settings
  # force2Ddimension setting is relative to the acquisition plane.
  #For example, the axial plane (0) corresponds to the acquisition plane (axial, sagittal or coronal) of the MRI volume.
  # Therefore, in most cases this setting should not be modified.
  force2Ddimension: 0
  force2D: false

  # Image discretization:
  binWidth: 5

  # first order specific settings:
  voxelArrayShift: 300

  # Misc:
  label: 1
